version: '3'

services:
  db:
    image: postgres
    restart: always
    healthcheck:
      interval: 10s
      retries: 10
      test:
        [
          'CMD-SHELL',
          'pg_isready',
          '-U',
          '${POSTGRES_USER}',
          '-P',
          '${POSTGRES_PASSWORD}'
        ]
      timeout: 45s
    environment:
      POSTGRES_DB: bc
      POSTGRES_USER: bc
      POSTGRES_PASSWORD: bc
    ports:
      - 5432:5432
    volumes:
    - ./pg.sql:/docker-entrypoint-initdb.d/pg.sql

  nodejs:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    environment:
      URL: http://localhost:3000
    ports:
     - '3000:3000'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    depends_on:
      - db

  proxy:
    build:
      context: './public'
      dockerfile: Dockerfile.local
    ports:
      - 8090:80
    depends_on:
      - nodejs
